#!/usr/bin/env bash
#
# spirex web installer — download the latest release jar and install a launcher.
# No git clone, no build step; just a JDK 21+ to run it.
#
#   curl -fsSL https://raw.githubusercontent.com/0x9r4ngu/spirex/main/get.sh | sudo bash
#
# Installs system-wide into /usr/local by default. Override the location with
# PREFIX (e.g. user-local, no sudo):
#
#   curl -fsSL .../get.sh | PREFIX="$HOME/.local" bash
#
set -euo pipefail

APP="spirex"
REPO="0x9r4ngu/spirex"
PREFIX="${PREFIX:-/usr/local}"
LIBDIR="$PREFIX/share/$APP"
BINDIR="$PREFIX/bin"
JAR_URL="https://github.com/$REPO/releases/latest/download/$APP.jar"

say() { printf '  %s\n' "$*"; }
ok()  { printf '  \033[32m[ok]\033[0m %s\n' "$*"; }
err() { printf '  \033[31m[!]\033[0m %s\n' "$*" >&2; }

echo
echo "  installing $APP ..."
echo

# 1. Java present? Detect it (incl. the invoking user's env under sudo), and
#    auto-install a JDK if it genuinely isn't there.
install_jdk() {
    local SUDO=""
    if [ "$(id -u)" -ne 0 ]; then
        command -v sudo >/dev/null 2>&1 && SUDO="sudo" || return 1
    fi
    export DEBIAN_FRONTEND=noninteractive
    if   command -v apt-get >/dev/null 2>&1; then
        $SUDO apt-get update -qq || true
        $SUDO apt-get install -y openjdk-21-jre-headless \
            || $SUDO apt-get install -y default-jre \
            || $SUDO apt-get install -y default-jdk
    elif command -v dnf >/dev/null 2>&1; then
        $SUDO dnf install -y java-21-openjdk-headless \
            || $SUDO dnf install -y java-latest-openjdk-headless
    elif command -v yum >/dev/null 2>&1; then
        $SUDO yum install -y java-21-openjdk
    elif command -v pacman >/dev/null 2>&1; then
        $SUDO pacman -Sy --noconfirm jre-openjdk
    elif command -v zypper >/dev/null 2>&1; then
        $SUDO zypper --non-interactive install java-21-openjdk
    elif command -v apk >/dev/null 2>&1; then
        $SUDO apk add --no-cache openjdk21-jre
    elif command -v brew >/dev/null 2>&1; then
        [ "$(id -u)" -eq 0 ] && return 1   # Homebrew refuses to run as root
        brew install openjdk
    else
        return 1
    fi
}

# When run via `sudo`, root's PATH may not include a user-installed JDK
# (SDKMAN, etc.). Check the original user's login shell before giving up.
USER_JAVA=""
if [ -n "${SUDO_USER:-}" ] && [ "${SUDO_USER}" != "root" ]; then
    USER_JAVA="$(sudo -u "$SUDO_USER" sh -lc 'command -v java' 2>/dev/null || true)"
fi

if command -v java >/dev/null 2>&1; then
    ok "found Java — $(java -version 2>&1 | head -1)"
elif [ -n "$USER_JAVA" ]; then
    ok "found Java in ${SUDO_USER}'s environment — $("$USER_JAVA" -version 2>&1 | head -1)"
    say "the launcher runs 'java' from your PATH, so you're set"
else
    say "Java not found — installing a JDK (this may take a minute) ..."
    if install_jdk && { hash -r 2>/dev/null; command -v java >/dev/null 2>&1; }; then
        ok "installed Java — $(java -version 2>&1 | head -1)"
    else
        err "couldn't install Java automatically. Install a JDK 21+ and re-run:"
        err "  Debian/Kali/Ubuntu:  sudo apt install default-jdk"
        err "  Fedora/RHEL:         sudo dnf install java-21-openjdk"
        err "  Arch:                sudo pacman -S jre-openjdk"
        err "  macOS (brew):        brew install openjdk"
        exit 1
    fi
fi

# 2. A downloader (curl or wget).
if command -v curl >/dev/null 2>&1; then
    fetch() { curl -fsSL "$1" -o "$2"; }
elif command -v wget >/dev/null 2>&1; then
    fetch() { wget -qO "$2" "$1"; }
else
    err "need curl or wget to download the release"
    exit 1
fi

# 3. Download the latest release jar.
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT
say "downloading latest $APP.jar ..."
if ! fetch "$JAR_URL" "$TMP" || [ ! -s "$TMP" ]; then
    err "download failed — no release jar at $JAR_URL yet?"
    exit 1
fi
ok "downloaded $APP.jar ($(wc -c < "$TMP") bytes)"

# 4. Install jar + launcher (need write access to PREFIX).
if ! mkdir -p "$LIBDIR" "$BINDIR" 2>/dev/null; then
    err "cannot write to $PREFIX — re-run with sudo, or set PREFIX=\$HOME/.local"
    exit 1
fi
install -m 0644 "$TMP" "$LIBDIR/$APP.jar"

cat > "$BINDIR/$APP" <<EOF
#!/usr/bin/env bash
# spirex launcher (generated by get.sh)
exec java -jar "$LIBDIR/$APP.jar" "\$@"
EOF
chmod 0755 "$BINDIR/$APP"
ok "installed launcher -> $BINDIR/$APP"

# 5. Make sure BINDIR is reachable.
case ":$PATH:" in
    *":$BINDIR:"*) ok "$BINDIR is on your PATH" ;;
    *) say "note: add $BINDIR to your PATH to run '$APP' from anywhere" ;;
esac

echo
ok "done. try:  $APP --help"
echo
