#!/usr/bin/env bash
#
# spirex web installer — download the latest release jar and install a launcher.
# No git clone, no build step; just a JDK 21+ to run it.
#
#   curl -fsSL https://raw.githubusercontent.com/0x9r4ngu/spirex/main/get.sh | sudo bash
#
# Installs system-wide into /usr/local by default. Override the location with
# PREFIX (e.g. user-local, no sudo):
#
#   curl -fsSL .../get.sh | PREFIX="$HOME/.local" bash
#
set -euo pipefail

APP="spirex"
REPO="0x9r4ngu/spirex"
PREFIX="${PREFIX:-/usr/local}"
LIBDIR="$PREFIX/share/$APP"
BINDIR="$PREFIX/bin"
JAR_URL="https://github.com/$REPO/releases/latest/download/$APP.jar"

say() { printf '  %s\n' "$*"; }
ok()  { printf '  \033[32m[ok]\033[0m %s\n' "$*"; }
err() { printf '  \033[31m[!]\033[0m %s\n' "$*" >&2; }

echo
echo "  installing $APP ..."
echo

# 1. Java present?
if ! command -v java >/dev/null 2>&1; then
    err "Java not found. Install a JDK 21+ first:"
    err "  Debian/Kali/Ubuntu:  sudo apt install default-jdk"
    err "  macOS (brew):        brew install openjdk"
    exit 1
fi
ok "found Java — $(java -version 2>&1 | head -1)"

# 2. A downloader (curl or wget).
if command -v curl >/dev/null 2>&1; then
    fetch() { curl -fsSL "$1" -o "$2"; }
elif command -v wget >/dev/null 2>&1; then
    fetch() { wget -qO "$2" "$1"; }
else
    err "need curl or wget to download the release"
    exit 1
fi

# 3. Download the latest release jar.
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT
say "downloading latest $APP.jar ..."
if ! fetch "$JAR_URL" "$TMP" || [ ! -s "$TMP" ]; then
    err "download failed — no release jar at $JAR_URL yet?"
    exit 1
fi
ok "downloaded $APP.jar ($(wc -c < "$TMP") bytes)"

# 4. Install jar + launcher (need write access to PREFIX).
if ! mkdir -p "$LIBDIR" "$BINDIR" 2>/dev/null; then
    err "cannot write to $PREFIX — re-run with sudo, or set PREFIX=\$HOME/.local"
    exit 1
fi
install -m 0644 "$TMP" "$LIBDIR/$APP.jar"

cat > "$BINDIR/$APP" <<EOF
#!/usr/bin/env bash
# spirex launcher (generated by get.sh)
exec java -jar "$LIBDIR/$APP.jar" "\$@"
EOF
chmod 0755 "$BINDIR/$APP"
ok "installed launcher -> $BINDIR/$APP"

# 5. Make sure BINDIR is reachable.
case ":$PATH:" in
    *":$BINDIR:"*) ok "$BINDIR is on your PATH" ;;
    *) say "note: add $BINDIR to your PATH to run '$APP' from anywhere" ;;
esac

echo
ok "done. try:  $APP --help"
echo
