#!/usr/bin/env bash
#
# spirex installer — builds the tool and installs a `spirex` launcher so you can
# run `spirex` from anywhere. No sudo, no dependencies (just a JDK).
#
#   ./install.sh
#   spirex --help
#
set -euo pipefail

APP="spirex"
DIR="$(cd "$(dirname "$0")" && pwd)"

# user-local prefix (override with: PREFIX=/usr/local sudo ./install.sh)
PREFIX="${PREFIX:-$HOME/.local}"
LIBDIR="$PREFIX/share/$APP"
BINDIR="$PREFIX/bin"

say()  { printf '  %s\n' "$*"; }
ok()   { printf '  \033[32m[ok]\033[0m %s\n' "$*"; }
err()  { printf '  \033[31m[!]\033[0m %s\n' "$*" >&2; }

echo
echo "  installing $APP ..."
echo

# 1. Java present?
if ! command -v java >/dev/null 2>&1; then
    err "Java not found. Install a JDK 21+ first:"
    err "  Debian/Kali/Ubuntu:  sudo apt install default-jdk"
    err "  macOS (brew):        brew install openjdk"
    exit 1
fi
JV="$(java -version 2>&1 | head -1)"
ok "found Java — $JV"

# 2. Build the jar
say "building $APP.jar ..."
"$DIR/build.sh" >/dev/null
ok "built $APP.jar"

# 3. Install jar + launcher
mkdir -p "$LIBDIR" "$BINDIR"
cp "$DIR/$APP.jar" "$LIBDIR/$APP.jar"

cat > "$BINDIR/$APP" <<EOF
#!/usr/bin/env bash
# spirex launcher (generated by install.sh)
exec java -jar "$LIBDIR/$APP.jar" "\$@"
EOF
chmod +x "$BINDIR/$APP"
ok "installed launcher -> $BINDIR/$APP"

# 4. Make sure BINDIR is on PATH
case ":$PATH:" in
    *":$BINDIR:"*)
        ok "$BINDIR is already on your PATH"
        ;;
    *)
        case "${SHELL:-}" in
            */zsh)  RC="$HOME/.zshrc" ;;
            */bash) RC="$HOME/.bashrc" ;;
            *)      RC="$HOME/.profile" ;;
        esac
        LINE="export PATH=\"$BINDIR:\$PATH\""
        if ! grep -qsF "$LINE" "$RC"; then
            printf '\n# added by spirex installer\n%s\n' "$LINE" >> "$RC"
        fi
        ok "added $BINDIR to PATH in $RC"
        say ""
        say "  -> run this once (or open a new terminal):  source $RC"
        ;;
esac

echo
ok "done. try:  $APP --help"
echo
